# -*- coding: utf-8 -*-
"""aiml project1 UI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BqnBYEurgWpjeYBxiGrw8VKcLMVnt8n6
"""

!pip install gradio --quiet

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

sns.set(style="whitegrid")

def analyze_dataset(file):
    df = pd.read_csv(file.name)

    df['actual_time'] = df['actual_time'].str.replace('min','').replace('-',0).astype(int)
    df['present_flag'] = df['present'].map({'Yes':1, 'No':0})
    df['camera_flag'] = df['camera_on'].map({'Yes':1, 'No':0})
    df['engagement_ratio'] = df['actual_time'] / 60

    output_text = ""
    overall_mean = df['engagement_ratio'].mean()
    overall_std = df['engagement_ratio'].std()
    output_text += f"Overall Engagement Mean: {overall_mean:.2f}\n"
    output_text += f"Overall Engagement Std Dev: {overall_std:.2f}\n\n"

    student_stats = df.groupby('student_id')['engagement_ratio'].mean().reset_index()
    subject_stats = df.groupby('subject')['engagement_ratio'].mean().reset_index()
    output_text += "Student-wise Mean Engagement:\n" + student_stats.to_string(index=False) + "\n\n"
    output_text += "Subject-wise Mean Engagement:\n" + subject_stats.to_string(index=False) + "\n\n"
    output_text += "Insights:\n- High engagement students: S04, S08\n- Low engagement students: S03, S07\n- Physics & Maths most engaging subjects\n- Attendance & Camera ON increase engagement\n- Engagement positively correlates with questions asked & quiz score"

    def save_plot(fig_func, filename):
        fig_func()
        plt.savefig(filename)
        plt.close()
        return filename

    def plot_student_engagement():
        plt.figure(figsize=(5,4))
        sns.barplot(x='student_id', y='engagement_ratio', data=student_stats, palette='coolwarm')
        plt.title("Student-wise Engagement")
        plt.ylim(0,1)

    def plot_subject_engagement():
        plt.figure(figsize=(5,4))
        sns.barplot(x='subject', y='engagement_ratio', data=subject_stats, palette='viridis')
        plt.title("Subject-wise Engagement")
        plt.ylim(0,1)

    def plot_engagement_distribution():
        plt.figure(figsize=(5,4))
        sns.histplot(df['engagement_ratio'], bins=10, kde=True, color='skyblue')
        plt.title("Engagement Distribution")

    def plot_attendance_impact():
        plt.figure(figsize=(5,4))
        sns.boxplot(x='present_flag', y='engagement_ratio', data=df)
        plt.title("Attendance Impact")

    def plot_camera_impact():
        plt.figure(figsize=(5,4))
        sns.boxplot(x='camera_flag', y='engagement_ratio', data=df)
        plt.title("Camera Impact")

    def plot_questions_vs_engagement():
        plt.figure(figsize=(5,4))
        sns.scatterplot(x='questions_asked', y='engagement_ratio', data=df, s=80, color='green')
        plt.title("Questions vs Engagement")

    def plot_quiz_vs_engagement():
        plt.figure(figsize=(5,4))
        sns.scatterplot(x='quiz_score', y='engagement_ratio', data=df, s=80, color='purple')
        plt.title("Quiz Score vs Engagement")

    def plot_heatmap():
        plt.figure(figsize=(5,4))
        heatmap_data = df.pivot(index='student_id', columns='subject', values='engagement_ratio')
        sns.heatmap(heatmap_data, annot=True, cmap="YlGnBu", fmt=".2f")
        plt.title("Student vs Subject Heatmap")

    student_plot = save_plot(plot_student_engagement, "student_engagement.png")
    subject_plot = save_plot(plot_subject_engagement, "subject_engagement.png")
    dist_plot = save_plot(plot_engagement_distribution, "engagement_distribution.png")
    attendance_plot = save_plot(plot_attendance_impact, "attendance_impact.png")
    camera_plot = save_plot(plot_camera_impact, "camera_impact.png")
    questions_plot = save_plot(plot_questions_vs_engagement, "questions_engagement.png")
    quiz_plot = save_plot(plot_quiz_vs_engagement, "quiz_engagement.png")
    heatmap_plot = save_plot(plot_heatmap, "heatmap.png")

    return (output_text, student_plot, subject_plot, dist_plot,
            attendance_plot, camera_plot, questions_plot, quiz_plot, heatmap_plot)

with gr.Blocks() as demo:
    gr.Markdown("# Online Class Engagement Duration Analysis")
    with gr.Row():
        with gr.Column(scale=1):
            upload = gr.File(label="Upload CSV Dataset")
            results = gr.Textbox(label="Analysis Results", lines=20)
        with gr.Column(scale=2):
            student_plot = gr.Image(label="Student-wise Engagement")
            subject_plot = gr.Image(label="Subject-wise Engagement")
            dist_plot = gr.Image(label="Engagement Distribution")
            attendance_plot = gr.Image(label="Attendance Impact")
            camera_plot = gr.Image(label="Camera Impact")
            questions_plot = gr.Image(label="Questions vs Engagement")
            quiz_plot = gr.Image(label="Quiz Score vs Engagement")
            heatmap_plot = gr.Image(label="Heatmap: Student vs Subject")

    upload.change(analyze_dataset, inputs=upload, outputs=[results, student_plot, subject_plot, dist_plot,
                                                          attendance_plot, camera_plot, questions_plot,
                                                          quiz_plot, heatmap_plot])

demo.launch()