# -*- coding: utf-8 -*-
"""aiml project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAV7FWOKAbOC1W0nwLmPqMFFNqOkXl1b
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

sns.set(style="whitegrid")

df = pd.read_csv("online_class_duration_dataset_10_students.csv")
df.head()

df['actual_time'] = df['actual_time'].str.replace('min','').replace('-',0).astype(int)

df['present_flag'] = df['present'].map({'Yes':1, 'No':0})

df['camera_flag'] = df['camera_on'].map({'Yes':1, 'No':0})

df['engagement_ratio'] = df['actual_time'] / 60

eng_stats = df['engagement_ratio'].describe()
print("Engagement Statistics:\n", eng_stats)

student_stats = df.groupby('student_id')['engagement_ratio'].agg(['mean','std','min','max'])
print("\nStudent-wise Engagement Stats:\n", student_stats)

subject_stats = df.groupby('subject')['engagement_ratio'].agg(['mean','std','min','max'])
print("\nSubject-wise Engagement Stats:\n", subject_stats)

student_avg = df.groupby('student_id')['engagement_ratio'].mean().reset_index()
plt.figure(figsize=(10,5))
sns.barplot(x='student_id', y='engagement_ratio', data=student_avg, palette='coolwarm')
plt.title("Average Engagement Ratio per Student")
plt.ylabel("Engagement Ratio")
plt.ylim(0,1)
plt.show()

subject_avg = df.groupby('subject')['engagement_ratio'].mean().reset_index()
plt.figure(figsize=(8,5))
sns.barplot(x='subject', y='engagement_ratio', data=subject_avg, palette='viridis')
plt.title("Average Engagement Ratio per Subject")
plt.ylabel("Engagement Ratio")
plt.ylim(0,1)
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['engagement_ratio'], bins=10, kde=True, color='skyblue')
plt.title("Engagement Ratio Distribution")
plt.xlabel("Engagement Ratio")
plt.ylabel("Number of Students")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='present_flag', y='engagement_ratio', data=df)
plt.title("Effect of Attendance on Engagement")
plt.xlabel("Present (1=Yes, 0=No)")
plt.ylabel("Engagement Ratio")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x='camera_flag', y='engagement_ratio', data=df)
plt.title("Effect of Camera ON on Engagement")
plt.xlabel("Camera On (1=Yes, 0=No)")
plt.ylabel("Engagement Ratio")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(x='questions_asked', y='engagement_ratio', data=df, s=100, color='green')
plt.title("Questions Asked vs Engagement")
plt.xlabel("Questions Asked")
plt.ylabel("Engagement Ratio")
plt.show()

corr_questions = df['questions_asked'].corr(df['engagement_ratio'])
print(f"Correlation (Questions vs Engagement): {corr_questions:.2f}")

plt.figure(figsize=(8,5))
sns.scatterplot(x='quiz_score', y='engagement_ratio', data=df, color='purple', s=100)
plt.title("Quiz Score vs Engagement")
plt.xlabel("Quiz Score")
plt.ylabel("Engagement Ratio")
plt.show()

corr_quiz = df['quiz_score'].corr(df['engagement_ratio'])
print(f"Correlation (Quiz Score vs Engagement): {corr_quiz:.2f}")

heatmap_data = df.pivot(index='student_id', columns='subject', values='engagement_ratio')
plt.figure(figsize=(10,6))
sns.heatmap(heatmap_data, annot=True, cmap="YlGnBu", fmt=".2f")
plt.title("Heatmap: Student vs Subject Engagement Ratio")
plt.show()